language: android
jdk: oraclejdk8

android:
  components:
  - tools # to get the new `repository-11.xml`
  - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
  - platform-tools
  - build-tools-27.0.2
  - android-27

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-armeabi-v7a-android-19
  - sys-img-x86-android-17

script: ./gradlew test

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
