language: android
jdk: oraclejdk8

android:
  components:
  - tools # to get the new `repository-11.xml`
  - platform-tools
  - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-armeabi-v7a-android-19
  - sys-img-x86-android-23

  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script: ./gradlew test

before_install:
- bash .travis-android-license-bugfix.sh

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
